version: '3'
services:
  frontend:
    build: ./
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - network-backend
  backend:
    build: ./server
    container_name: backend
    ports:
      - "5005:5005"
    networks:
      - network-backend
  database-postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    volumes:
     - ./db/.pgdata:/var/lib/postgresql
     - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks: 
     - network-backend
    environment:
      - POSTGRES_DB:postgres
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:docker
      - POSTGRES_HOST_AUTH_METHOD=trust

networks:
  network-backend: